# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-14 18:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dim_Esps',
            fields=[
                ('Modes', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('Esps', models.CharField(max_length=1000, null=True)),
                ('Time', models.CharField(max_length=1000, null=True)),
                ('Light_dim', models.CharField(max_length=1000, null=True)),
                ('ChangeDate', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'Dim_Esps',
            },
        ),
    ]
