# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-11 11:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JTS_Images',
            fields=[
                ('ImgId', models.AutoField(primary_key=True, serialize=False)),
                ('Image', models.FileField(upload_to=b'')),
                ('StatusActive', models.BooleanField(default=True)),
                ('ChangeDate', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'JTS_Images',
            },
        ),
    ]
