# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-20 16:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DtD_Units',
            fields=[
                ('UnitId', models.AutoField(primary_key=True, serialize=False)),
                ('Long', models.CharField(max_length=125, null=True)),
                ('Lat', models.CharField(max_length=125, null=True)),
                ('Operation', models.CharField(max_length=50, null=True)),
                ('ChangeBy', models.CharField(max_length=125, null=True)),
                ('ChangeDate', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'DtD_Units',
            },
        ),
        migrations.CreateModel(
            name='DtD_Users',
            fields=[
                ('Username', models.CharField(max_length=125, primary_key=True, serialize=False)),
                ('Password', models.CharField(max_length=255, null=True)),
                ('Address', models.TextField(blank=True, null=True)),
                ('Company', models.CharField(max_length=255, null=True)),
                ('Mobile', models.CharField(max_length=50, null=True)),
                ('Email', models.CharField(max_length=50, null=True)),
                ('ChangeDate', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'DtD_Users',
            },
        ),
    ]
