# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-20 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DuskToDawnApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dtd_units',
            name='UnitDesc',
            field=models.CharField(max_length=125, null=True),
        ),
    ]
