# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-28 16:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('DuskToDawnApp', '0004_auto_20180822_1347'),
    ]

    operations = [
        migrations.CreateModel(
            name='DtD_Unit_Details',
            fields=[
                ('UDId', models.AutoField(primary_key=True, serialize=False)),
                ('Sr', models.CharField(max_length=125, null=True)),
                ('Ss', models.CharField(max_length=125, null=True)),
                ('Dw', models.CharField(max_length=125, null=True)),
                ('Tw', models.CharField(max_length=125, null=True)),
                ('Ab', models.CharField(max_length=125, null=True)),
                ('ChangeBy', models.CharField(max_length=125, null=True)),
                ('ChangeDate', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'DtD_Unit_Details',
            },
        ),
        migrations.RemoveField(
            model_name='dtd_units',
            name='Ab',
        ),
        migrations.RemoveField(
            model_name='dtd_units',
            name='Dw',
        ),
        migrations.RemoveField(
            model_name='dtd_units',
            name='Sr',
        ),
        migrations.RemoveField(
            model_name='dtd_units',
            name='Ss',
        ),
        migrations.RemoveField(
            model_name='dtd_units',
            name='Tw',
        ),
        migrations.AddField(
            model_name='dtd_unit_details',
            name='UnitId',
            field=models.ForeignKey(db_column='UnitId', on_delete=django.db.models.deletion.CASCADE, to='DuskToDawnApp.DtD_Units'),
        ),
    ]
