# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-28 16:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DuskToDawnApp', '0005_auto_20180828_1620'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dtd_unit_details',
            old_name='Ab',
            new_name='Type',
        ),
        migrations.RemoveField(
            model_name='dtd_unit_details',
            name='Dw',
        ),
        migrations.RemoveField(
            model_name='dtd_unit_details',
            name='Sr',
        ),
        migrations.RemoveField(
            model_name='dtd_unit_details',
            name='Ss',
        ),
        migrations.RemoveField(
            model_name='dtd_unit_details',
            name='Tw',
        ),
    ]
