# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-28 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DuskToDawnApp', '0006_auto_20180828_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='dtd_unit_details',
            name='Time',
            field=models.CharField(max_length=125, null=True),
        ),
    ]
