# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-29 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DuskToDawnApp', '0007_dtd_unit_details_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dtd_unit_details',
            old_name='Time',
            new_name='Hours',
        ),
        migrations.AddField(
            model_name='dtd_unit_details',
            name='Mns',
            field=models.CharField(max_length=125, null=True),
        ),
        migrations.AddField(
            model_name='dtd_unit_details',
            name='PosNeg',
            field=models.CharField(max_length=125, null=True),
        ),
    ]
