# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-06 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DuskToDawnApp', '0008_auto_20180829_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='dtd_units',
            name='UnitName',
            field=models.CharField(max_length=125, null=True),
        ),
    ]
