# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-06 12:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DuskToDawnApp', '0009_dtd_units_unitname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dtd_units',
            old_name='UnitName',
            new_name='UnitMac',
        ),
    ]
