# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-12 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DuskToDawnApp', '0010_auto_20180906_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='dtd_unit_details',
            name='Status',
            field=models.CharField(max_length=125, null=True),
        ),
    ]
