# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-14 16:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Power_Voltage',
            fields=[
                ('Power_Id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Power_Voltage', models.IntegerField()),
                ('ChangeBy', models.CharField(max_length=50, null=True)),
                ('ChangeDate', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'Power_Voltage',
            },
        ),
        migrations.CreateModel(
            name='Power_Voltage_History',
            fields=[
                ('ActivityId', models.AutoField(primary_key=True, serialize=False)),
                ('Power_Id', models.CharField(max_length=50)),
                ('Power_Voltage', models.IntegerField()),
                ('ChangeDate', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('ChangeBy', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'Power_Voltage_History',
            },
        ),
    ]
