# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-20 17:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UK_Unit_History',
            fields=[
                ('UHId', models.AutoField(primary_key=True, serialize=False)),
                ('MacId', models.CharField(max_length=125, unique=True)),
                ('Temp', models.IntegerField(max_length=125, null=True)),
                ('WaterLevel', models.IntegerField(blank=True, null=True)),
                ('Ph', models.FloatField(blank=True, null=True)),
                ('EC', models.FloatField(blank=True, null=True)),
                ('Ppm', models.IntegerField(blank=True, null=True)),
                ('ChangeDate', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'UK_Unit_History',
            },
        ),
        migrations.CreateModel(
            name='UK_Unit_Params',
            fields=[
                ('UnitId', models.AutoField(primary_key=True, serialize=False)),
                ('MacId', models.CharField(max_length=125, unique=True)),
                ('Temp', models.IntegerField(max_length=125, null=True)),
                ('WaterLevel', models.IntegerField(blank=True, null=True)),
                ('Ph', models.FloatField(blank=True, null=True)),
                ('EC', models.FloatField(blank=True, null=True)),
                ('Ppm', models.IntegerField(blank=True, null=True)),
                ('ChangeDate', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'UK_Unit_Params',
            },
        ),
        migrations.AddField(
            model_name='uk_unit_history',
            name='UnitId',
            field=models.ForeignKey(db_column='UnitId', on_delete=django.db.models.deletion.CASCADE, to='UrbanKisanApp.UK_Unit_Params'),
        ),
    ]
