# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-21 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UrbanKisanApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uk_unit_history',
            name='MacId',
            field=models.CharField(max_length=125, null=True),
        ),
    ]
