# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-14 17:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset_Rooms',
            fields=[
                ('Room_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('Room_desc', models.CharField(max_length=255)),
                ('Change_Date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'Asset_Rooms',
            },
        ),
        migrations.CreateModel(
            name='Asset_SSID',
            fields=[
                ('Ssid', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('Ssid_tag', models.CharField(max_length=255, null=True)),
                ('Change_Date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('Room_id', models.ForeignKey(db_column='Room_id', on_delete=django.db.models.deletion.CASCADE, to='AssetTrackerApp.Asset_Rooms')),
            ],
            options={
                'db_table': 'Asset_SSID',
            },
        ),
        migrations.CreateModel(
            name='Asset_Ssid_Str',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Str_ssid', models.CharField(max_length=10, null=True)),
                ('Change_Date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('Room_id', models.ForeignKey(db_column='Room_id', on_delete=django.db.models.deletion.CASCADE, to='AssetTrackerApp.Asset_Rooms')),
                ('Ssid', models.ForeignKey(db_column='Ssid', on_delete=django.db.models.deletion.CASCADE, to='AssetTrackerApp.Asset_SSID')),
            ],
            options={
                'db_table': 'Asset_Ssid_Str',
            },
        ),
    ]
