# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-08 15:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lookup',
            fields=[
                ('LU_ID', models.AutoField(primary_key=True, serialize=False)),
                ('LU_Value', models.CharField(max_length=512, null=True)),
                ('IsActive', models.NullBooleanField()),
                ('ChangeDate', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'Lookup',
            },
        ),
        migrations.CreateModel(
            name='SysLookup',
            fields=[
                ('SLU_ID', models.AutoField(primary_key=True, serialize=False)),
                ('SysLookup_Desc', models.CharField(max_length=512, null=True)),
                ('IsActive', models.NullBooleanField()),
                ('ChangeDate', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'SysLookup',
            },
        ),
        migrations.AddField(
            model_name='lookup',
            name='SLU_ID',
            field=models.ForeignKey(db_column='Syslookup_ID', on_delete=django.db.models.deletion.CASCADE, to='FMSApp.SysLookup'),
        ),
    ]
