# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-14 17:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('GrowBoxApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GB_GrowData_History',
            fields=[
                ('GBHId', models.AutoField(primary_key=True, serialize=False)),
                ('Macid', models.CharField(max_length=50, null=True)),
                ('Chamber1Temp', models.FloatField(blank=True, null=True)),
                ('Chamber1Humi', models.FloatField(blank=True, null=True)),
                ('Chamber2Temp', models.FloatField(blank=True, null=True)),
                ('Chamber2Humi', models.FloatField(blank=True, null=True)),
                ('Chamber3Temp', models.FloatField(blank=True, null=True)),
                ('Chamber3Humi', models.FloatField(blank=True, null=True)),
                ('ChillerTemp', models.FloatField(blank=True, null=True)),
                ('ChangeBy', models.CharField(max_length=50, null=True)),
                ('ChangeDate', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('GBId', models.ForeignKey(db_column='GBId', default=1, on_delete=django.db.models.deletion.CASCADE, to='GrowBoxApp.GB_GrowData')),
            ],
            options={
                'db_table': 'GB_GrowData_History',
            },
        ),
    ]
