# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-14 13:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Current_Status',
            fields=[
                ('TowerId', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Status', models.CharField(max_length=10)),
                ('ChangeDate', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('ChangeBy', models.CharField(max_length=50, null=True)),
                ('Operate', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'Current_Status',
            },
        ),
        migrations.CreateModel(
            name='Current_Status_History',
            fields=[
                ('ActivityId', models.AutoField(primary_key=True, serialize=False)),
                ('TowerId', models.CharField(max_length=50)),
                ('Status', models.CharField(max_length=10)),
                ('ChangeDate', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('ChangeBy', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'Current_Status_History',
            },
        ),
        migrations.CreateModel(
            name='Login_Users',
            fields=[
                ('Uname', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Pass', models.CharField(max_length=50)),
                ('ChangeDate', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'Login_Users',
            },
        ),
    ]
