# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-24 17:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prepaid_Cat_Fares',
            fields=[
                ('CatFareId', models.AutoField(primary_key=True, serialize=False)),
                ('Units', models.IntegerField(blank=True, null=True)),
                ('Domestic', models.FloatField(blank=True, null=True)),
                ('Commercial', models.FloatField(blank=True, null=True)),
                ('ChangeDate', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'Prepaid_Cat_Fares',
            },
        ),
        migrations.CreateModel(
            name='Prepaid_Category',
            fields=[
                ('CatId', models.AutoField(primary_key=True, serialize=False)),
                ('CatDesc', models.CharField(max_length=255, null=True)),
                ('ChangeBy', models.CharField(max_length=255, null=True)),
                ('ChangeDate', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'Prepaid_Category',
            },
        ),
        migrations.CreateModel(
            name='Prepaid_Meters',
            fields=[
                ('MeterId', models.AutoField(primary_key=True, serialize=False)),
                ('MacID', models.CharField(max_length=125, unique=True)),
                ('Units', models.FloatField(blank=True, null=True)),
                ('ChangeBy', models.CharField(max_length=255, null=True)),
                ('ChangeDate', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('CatId', models.ForeignKey(db_column='CatId', on_delete=django.db.models.deletion.CASCADE, to='PrepaidRCApp.Prepaid_Category')),
            ],
            options={
                'db_table': 'Prepaid_Meters',
            },
        ),
        migrations.CreateModel(
            name='Prepaid_Payment',
            fields=[
                ('TransactionId', models.AutoField(primary_key=True, serialize=False)),
                ('Paid', models.FloatField(blank=True, null=True)),
                ('ChangeBy', models.CharField(max_length=255, null=True)),
                ('ChangeDate', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('CatId', models.ForeignKey(db_column='CatId', on_delete=django.db.models.deletion.CASCADE, to='PrepaidRCApp.Prepaid_Category')),
                ('MeterId', models.ForeignKey(db_column='MeterId', on_delete=django.db.models.deletion.CASCADE, to='PrepaidRCApp.Prepaid_Meters')),
            ],
            options={
                'db_table': 'Prepaid_Payment',
            },
        ),
        migrations.CreateModel(
            name='Prepaid_Usage_History',
            fields=[
                ('MeterIdH', models.AutoField(primary_key=True, serialize=False)),
                ('Units', models.FloatField(blank=True, null=True)),
                ('ChangeBy', models.CharField(max_length=255, null=True)),
                ('ChangeDate', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('MeterId', models.ForeignKey(db_column='MeterId', on_delete=django.db.models.deletion.CASCADE, to='PrepaidRCApp.Prepaid_Meters')),
            ],
            options={
                'db_table': 'Prepaid_Usage_History',
            },
        ),
        migrations.CreateModel(
            name='Prepaid_Users',
            fields=[
                ('UserId', models.AutoField(primary_key=True, serialize=False)),
                ('Username', models.CharField(max_length=125, unique=True)),
                ('Password', models.CharField(max_length=255, null=True)),
                ('Phone', models.CharField(max_length=255, null=True)),
                ('Email', models.CharField(max_length=255, null=True)),
                ('ChangeBy', models.CharField(max_length=255, null=True)),
                ('ChangeDate', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'Prepaid_Users',
            },
        ),
        migrations.AddField(
            model_name='prepaid_payment',
            name='UserId',
            field=models.ForeignKey(db_column='UserId', on_delete=django.db.models.deletion.CASCADE, to='PrepaidRCApp.Prepaid_Users'),
        ),
        migrations.AddField(
            model_name='prepaid_meters',
            name='UserId',
            field=models.ForeignKey(db_column='UserId', on_delete=django.db.models.deletion.CASCADE, to='PrepaidRCApp.Prepaid_Users'),
        ),
    ]
