# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-24 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PrepaidRCApp', '0003_auto_20180924_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prepaid_cat_fares',
            name='U100',
            field=models.FloatField(blank=True, db_column='U51T100', null=True),
        ),
        migrations.AlterField(
            model_name='prepaid_cat_fares',
            name='U50',
            field=models.FloatField(blank=True, db_column='U0T50', null=True),
        ),
    ]
