# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-24 18:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PrepaidRCApp', '0004_auto_20180924_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='prepaid_users',
            name='CatId',
            field=models.ForeignKey(db_column='CatId', default='', on_delete=django.db.models.deletion.CASCADE, to='PrepaidRCApp.Prepaid_Category'),
            preserve_default=False,
        ),
    ]
