# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-08 18:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AC_Admin',
            fields=[
                ('AdminId', models.AutoField(primary_key=True, serialize=False)),
                ('AdminDesc', models.CharField(max_length=50, null=True)),
                ('StatusActive', models.BooleanField(default=True)),
                ('ChangeDate', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'AC_Admin',
            },
        ),
        migrations.CreateModel(
            name='AC_City',
            fields=[
                ('CityId', models.AutoField(primary_key=True, serialize=False)),
                ('CityDesc', models.CharField(max_length=50, null=True)),
                ('setTemp', models.IntegerField(blank=True, null=True)),
                ('ChangeBy', models.CharField(max_length=50, null=True)),
                ('StatusActive', models.BooleanField(default=True)),
                ('ChangeDate', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'AC_City',
            },
        ),
        migrations.CreateModel(
            name='AC_Clients',
            fields=[
                ('ClientId', models.AutoField(primary_key=True, serialize=False)),
                ('ClientName', models.CharField(max_length=50, null=True)),
                ('StatusActive', models.BooleanField(default=True)),
                ('ChangeDate', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'AC_Clients',
            },
        ),
        migrations.CreateModel(
            name='AC_Floors',
            fields=[
                ('FloorId', models.AutoField(primary_key=True, serialize=False)),
                ('FloorDesc', models.CharField(max_length=50, null=True)),
                ('ChangeBy', models.CharField(max_length=50, null=True)),
                ('StatusActive', models.BooleanField(default=True)),
                ('ChangeDate', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('CityId', models.ForeignKey(db_column='CityId', on_delete=django.db.models.deletion.CASCADE, to='GenericACApp.AC_City')),
            ],
            options={
                'db_table': 'AC_Floors',
            },
        ),
        migrations.CreateModel(
            name='AC_Images',
            fields=[
                ('ImgId', models.AutoField(primary_key=True, serialize=False)),
                ('Image', models.FileField(upload_to=b'')),
                ('StatusActive', models.BooleanField(default=True)),
                ('ChangeDate', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'AC_Images',
            },
        ),
        migrations.CreateModel(
            name='AC_Input_History',
            fields=[
                ('IHId', models.AutoField(primary_key=True, serialize=False)),
                ('IpMacid', models.CharField(max_length=50, null=True)),
                ('IpName', models.CharField(max_length=50, null=True)),
                ('Abrivation', models.CharField(max_length=50, null=True)),
                ('Temp', models.FloatField(blank=True, null=True)),
                ('Motion', models.IntegerField(blank=True, null=True)),
                ('ChangeBy', models.CharField(max_length=50, null=True)),
                ('ChangeDate', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'AC_Input_History',
            },
        ),
        migrations.CreateModel(
            name='AC_Input_Units',
            fields=[
                ('IpId', models.AutoField(primary_key=True, serialize=False)),
                ('IpMacid', models.CharField(max_length=50, null=True)),
                ('IpName', models.CharField(max_length=50, null=True)),
                ('Abrivation', models.CharField(max_length=50, null=True)),
                ('Temp', models.FloatField(blank=True, null=True)),
                ('Motion', models.IntegerField(blank=True, null=True)),
                ('ChangeBy', models.CharField(max_length=50, null=True)),
                ('StatusActive', models.BooleanField(default=True)),
                ('ChangeDate', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('CityId', models.ForeignKey(db_column='CityId', on_delete=django.db.models.deletion.CASCADE, to='GenericACApp.AC_City')),
                ('FloorId', models.ForeignKey(db_column='FloorId', on_delete=django.db.models.deletion.CASCADE, to='GenericACApp.AC_Floors')),
            ],
            options={
                'db_table': 'AC_Input_Units',
            },
        ),
        migrations.CreateModel(
            name='AC_Operate_History',
            fields=[
                ('OHId', models.AutoField(primary_key=True, serialize=False)),
                ('OpMacid', models.CharField(max_length=50, null=True)),
                ('OpName', models.CharField(max_length=50, null=True)),
                ('Abrivation', models.CharField(max_length=50, null=True)),
                ('Fan', models.CharField(max_length=50, null=True)),
                ('Status', models.CharField(max_length=50, null=True)),
                ('setTemp', models.IntegerField(blank=True, null=True)),
                ('Current', models.FloatField(blank=True, null=True)),
                ('Voltage', models.FloatField(blank=True, null=True)),
                ('Power', models.FloatField(blank=True, null=True)),
                ('MotionE', models.IntegerField(blank=True, null=True)),
                ('ChangeBy', models.CharField(max_length=50, null=True)),
                ('ChangeDate', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'AC_Operate_History',
            },
        ),
        migrations.CreateModel(
            name='AC_Operate_Units',
            fields=[
                ('OpId', models.AutoField(primary_key=True, serialize=False)),
                ('OpMacid', models.CharField(max_length=50, null=True)),
                ('OpName', models.CharField(max_length=50, null=True)),
                ('Abrivation', models.CharField(max_length=50, null=True)),
                ('Fan', models.CharField(max_length=50, null=True)),
                ('Status', models.CharField(max_length=50, null=True)),
                ('setTemp', models.IntegerField(blank=True, null=True)),
                ('Current', models.FloatField(blank=True, null=True)),
                ('Voltage', models.FloatField(blank=True, null=True)),
                ('Power', models.FloatField(blank=True, null=True)),
                ('MotionE', models.IntegerField(blank=True, null=True)),
                ('ChangeBy', models.CharField(max_length=50, null=True)),
                ('StatusActive', models.BooleanField(default=True)),
                ('ChangeDate', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('CityId', models.ForeignKey(db_column='CityId', on_delete=django.db.models.deletion.CASCADE, to='GenericACApp.AC_City')),
                ('FloorId', models.ForeignKey(db_column='FloorId', on_delete=django.db.models.deletion.CASCADE, to='GenericACApp.AC_Floors')),
            ],
            options={
                'db_table': 'AC_Operate_Units',
            },
        ),
        migrations.CreateModel(
            name='AC_Power_History',
            fields=[
                ('PHId', models.AutoField(primary_key=True, serialize=False)),
                ('PMacid', models.CharField(max_length=50, null=True)),
                ('PName', models.CharField(max_length=50, null=True)),
                ('Abrivation', models.CharField(max_length=50, null=True)),
                ('Current', models.FloatField(blank=True, null=True)),
                ('Voltage', models.FloatField(blank=True, null=True)),
                ('Power', models.FloatField(blank=True, null=True)),
                ('ChangeBy', models.CharField(max_length=50, null=True)),
                ('ChangeDate', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'AC_Power_History',
            },
        ),
        migrations.CreateModel(
            name='AC_Power_Units',
            fields=[
                ('PId', models.AutoField(primary_key=True, serialize=False)),
                ('PMacid', models.CharField(max_length=50, null=True)),
                ('PName', models.CharField(max_length=50, null=True)),
                ('Abrivation', models.CharField(max_length=50, null=True)),
                ('Current', models.FloatField(blank=True, null=True)),
                ('Voltage', models.FloatField(blank=True, null=True)),
                ('Power', models.FloatField(blank=True, null=True)),
                ('ChangeBy', models.CharField(max_length=50, null=True)),
                ('StatusActive', models.BooleanField(default=True)),
                ('ChangeDate', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('CityId', models.ForeignKey(db_column='CityId', on_delete=django.db.models.deletion.CASCADE, to='GenericACApp.AC_City')),
                ('FloorId', models.ForeignKey(db_column='FloorId', on_delete=django.db.models.deletion.CASCADE, to='GenericACApp.AC_Floors')),
            ],
            options={
                'db_table': 'AC_Power_Units',
            },
        ),
        migrations.CreateModel(
            name='AC_Premise',
            fields=[
                ('PremiseId', models.AutoField(primary_key=True, serialize=False)),
                ('PremiseDesc', models.CharField(max_length=50, null=True)),
                ('setTemp', models.IntegerField(blank=True, null=True)),
                ('ChangeBy', models.CharField(max_length=50, null=True)),
                ('StatusActive', models.BooleanField(default=True)),
                ('ChangeDate', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('CityId', models.ForeignKey(db_column='CityId', on_delete=django.db.models.deletion.CASCADE, to='GenericACApp.AC_City')),
            ],
            options={
                'db_table': 'AC_Premise',
            },
        ),
        migrations.CreateModel(
            name='AC_Rooms',
            fields=[
                ('RoomId', models.AutoField(primary_key=True, serialize=False)),
                ('RoomDesc', models.CharField(max_length=50, null=True)),
                ('ChangeBy', models.CharField(max_length=50, null=True)),
                ('StatusActive', models.BooleanField(default=True)),
                ('ChangeDate', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('CityId', models.ForeignKey(db_column='CityId', on_delete=django.db.models.deletion.CASCADE, to='GenericACApp.AC_City')),
                ('FloorId', models.ForeignKey(db_column='FloorId', on_delete=django.db.models.deletion.CASCADE, to='GenericACApp.AC_Floors')),
                ('PremiseId', models.ForeignKey(db_column='PremiseId', on_delete=django.db.models.deletion.CASCADE, to='GenericACApp.AC_Premise')),
            ],
            options={
                'db_table': 'AC_Rooms',
            },
        ),
        migrations.CreateModel(
            name='AC_Saved_Units',
            fields=[
                ('SUId', models.AutoField(primary_key=True, serialize=False)),
                ('Saved', models.FloatField(blank=True, null=True)),
                ('ChangeBy', models.CharField(default='jts_admin', max_length=50, null=True)),
                ('StatusActive', models.BooleanField(default=True)),
                ('ChangeDate', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'AC_Saved_Units',
            },
        ),
        migrations.CreateModel(
            name='AC_Units',
            fields=[
                ('UnitId', models.AutoField(primary_key=True, serialize=False)),
                ('UnitDesc', models.CharField(max_length=50, null=True)),
                ('ChangeBy', models.CharField(max_length=50, null=True)),
                ('StatusActive', models.BooleanField(default=True)),
                ('ChangeDate', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'AC_Units',
            },
        ),
        migrations.CreateModel(
            name='AC_Users',
            fields=[
                ('UserId', models.AutoField(primary_key=True, serialize=False)),
                ('Username', models.CharField(max_length=50, unique=True)),
                ('Password', models.CharField(max_length=50, null=True)),
                ('TransPass', models.CharField(max_length=50, null=True)),
                ('ChangeBy', models.CharField(max_length=50, null=True)),
                ('StatusActive', models.BooleanField(default=True)),
                ('ChangeDate', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('ClientId', models.ForeignKey(db_column='ClientId', default=1, on_delete=django.db.models.deletion.CASCADE, to='GenericACApp.AC_Clients')),
                ('ImgId', models.ForeignKey(db_column='ImgId', default=1, on_delete=django.db.models.deletion.CASCADE, to='GenericACApp.AC_Images')),
                ('Role', models.ForeignKey(db_column='Role', default=1, on_delete=django.db.models.deletion.CASCADE, to='GenericACApp.AC_Admin')),
            ],
            options={
                'db_table': 'AC_Users',
            },
        ),
        migrations.AddField(
            model_name='ac_saved_units',
            name='UnitId',
            field=models.ForeignKey(db_column='UnitId', on_delete=django.db.models.deletion.CASCADE, to='GenericACApp.AC_Units'),
        ),
        migrations.AddField(
            model_name='ac_power_units',
            name='PremiseId',
            field=models.ForeignKey(db_column='PremiseId', on_delete=django.db.models.deletion.CASCADE, to='GenericACApp.AC_Premise'),
        ),
        migrations.AddField(
            model_name='ac_power_units',
            name='RoomId',
            field=models.ForeignKey(db_column='RoomId', on_delete=django.db.models.deletion.CASCADE, to='GenericACApp.AC_Rooms'),
        ),
        migrations.AddField(
            model_name='ac_power_units',
            name='UnitId',
            field=models.ForeignKey(db_column='UnitId', on_delete=django.db.models.deletion.CASCADE, to='GenericACApp.AC_Units'),
        ),
        migrations.AddField(
            model_name='ac_power_history',
            name='PId',
            field=models.ForeignKey(db_column='PId', on_delete=django.db.models.deletion.CASCADE, to='GenericACApp.AC_Power_Units'),
        ),
        migrations.AddField(
            model_name='ac_power_history',
            name='UnitId',
            field=models.ForeignKey(db_column='UnitId', default=1, on_delete=django.db.models.deletion.CASCADE, to='GenericACApp.AC_Units'),
        ),
        migrations.AddField(
            model_name='ac_operate_units',
            name='PremiseId',
            field=models.ForeignKey(db_column='PremiseId', on_delete=django.db.models.deletion.CASCADE, to='GenericACApp.AC_Premise'),
        ),
        migrations.AddField(
            model_name='ac_operate_units',
            name='RoomId',
            field=models.ForeignKey(db_column='RoomId', on_delete=django.db.models.deletion.CASCADE, to='GenericACApp.AC_Rooms'),
        ),
        migrations.AddField(
            model_name='ac_operate_units',
            name='UnitId',
            field=models.ForeignKey(db_column='UnitId', on_delete=django.db.models.deletion.CASCADE, to='GenericACApp.AC_Units'),
        ),
        migrations.AddField(
            model_name='ac_operate_history',
            name='OpId',
            field=models.ForeignKey(db_column='OpId', on_delete=django.db.models.deletion.CASCADE, to='GenericACApp.AC_Operate_Units'),
        ),
        migrations.AddField(
            model_name='ac_operate_history',
            name='UnitId',
            field=models.ForeignKey(db_column='UnitId', default=1, on_delete=django.db.models.deletion.CASCADE, to='GenericACApp.AC_Units'),
        ),
        migrations.AddField(
            model_name='ac_input_units',
            name='PremiseId',
            field=models.ForeignKey(db_column='PremiseId', on_delete=django.db.models.deletion.CASCADE, to='GenericACApp.AC_Premise'),
        ),
        migrations.AddField(
            model_name='ac_input_units',
            name='RoomId',
            field=models.ForeignKey(db_column='RoomId', on_delete=django.db.models.deletion.CASCADE, to='GenericACApp.AC_Rooms'),
        ),
        migrations.AddField(
            model_name='ac_input_units',
            name='UnitId',
            field=models.ForeignKey(db_column='UnitId', on_delete=django.db.models.deletion.CASCADE, to='GenericACApp.AC_Units'),
        ),
        migrations.AddField(
            model_name='ac_input_history',
            name='IpId',
            field=models.ForeignKey(db_column='IpId', on_delete=django.db.models.deletion.CASCADE, to='GenericACApp.AC_Input_Units'),
        ),
        migrations.AddField(
            model_name='ac_input_history',
            name='UnitId',
            field=models.ForeignKey(db_column='UnitId', default=1, on_delete=django.db.models.deletion.CASCADE, to='GenericACApp.AC_Units'),
        ),
        migrations.AddField(
            model_name='ac_floors',
            name='PremiseId',
            field=models.ForeignKey(db_column='PremiseId', on_delete=django.db.models.deletion.CASCADE, to='GenericACApp.AC_Premise'),
        ),
        migrations.AddIndex(
            model_name='ac_power_history',
            index=models.Index(fields=['ChangeDate'], name='ChangeDate_idx'),
        ),
        migrations.AddIndex(
            model_name='ac_operate_history',
            index=models.Index(fields=['ChangeDate'], name='ChangeDate_idx'),
        ),
        migrations.AddIndex(
            model_name='ac_input_history',
            index=models.Index(fields=['ChangeDate'], name='ChangeDate_idx'),
        ),
    ]
