# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-21 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GenericACApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ac_users',
            name='Version',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
