# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-01 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GenericACApp', '0002_ac_users_version'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ac_input_history',
            index=models.Index(fields=['UnitId'], name='UnitId_idx'),
        ),
    ]
