# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-01 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GenericACApp', '0003_auto_20181201_1246'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ac_operate_history',
            index=models.Index(fields=['UnitId'], name='UnitId_idx'),
        ),
        migrations.AddIndex(
            model_name='ac_power_history',
            index=models.Index(fields=['UnitId'], name='UnitId_idx'),
        ),
    ]
